baseURL = 'https://dmien0322.github.io/blog/'
languageCode = "en-us"
theme = "anubis2"
title = "dongmien"

[params.author]
name = "dongmien"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/